# Generated by Django 4.0.2 on 2022-02-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.EmailField(default='asd@asdf.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
