# Generated by Django 4.0.2 on 2022-02-20 04:29

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_image_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=tinymce.models.HTMLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
