# Generated by Django 4.0.2 on 2022-02-23 23:22

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_image_caption_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('order',), name='unique_image_order'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('order',), name='unique_project_order'),
        ),
    ]
