# Generated by Django 4.0.2 on 2022-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0005_email_status_alter_email_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="status",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Delivery Status"
            ),
        ),
    ]
