# Generated by Django 4.0.2 on 2022-02-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0006_alter_email_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
