# Generated by Django 4.0.2 on 2022-02-27 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0007_project_published"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="image",
            name="unique_image_order",
        ),
    ]
