# Generated by Django 4.0.2 on 2022-03-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_image_unique_image_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('html', models.CharField(help_text='Paste embed HTML here. Warning, this will be rendered directly to page as |safe', max_length=1500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='embeds',
            field=models.ManyToManyField(to='Main.Embed'),
        ),
    ]
