# Generated by Django 4.0.2 on 2022-03-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_project_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
