# Generated by Django 4.2.3 on 2023-07-31 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0015_project_last_modified"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Email",
        ),
    ]
